name: Bjorn Amundsen
favicon: null
layout_spectrum: 0.5896413566078991
typography_spectrum: 0.03426210721954703
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.7975760393310338
  lightness: 0.045892133843153715
  saturation: 0.4931340010371059
  rhythmicContrast: 0.21044017374515533
purpose: []
